services:
  utserver:
    image: utserver:latest
    build: ./
    ports:
      - 8080:8080
      - 6666:6666
    volumes:
      - ./incoming:/mnt/incoming
      - ./server.conf:/root/.config/qBittorrent/qBittorrent.conf
