[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=false
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/root/.local/share/qBittorrent/logs

[BitTorrent]
MergeTrackersEnabled=true
Session\AnonymousModeEnabled=true
Session\DefaultSavePath=/mnt/incoming
Session\Encryption=1
Session\ExcludedFileNames=
Session\Port=49644
Session\QueueingSystemEnabled=false
Session\SSL\Port=38012
Session\TempPath=/mnt/incoming/torrents
Session\TempPathEnabled=true

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=false

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=@Invalid()
