[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=false
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/data/logs

[BitTorrent]
Session\AddTorrentStopped=false
Session\AnonymousModeEnabled=true
Session\DefaultSavePath=/downloads
Session\Encryption=1
Session\ExcludedFileNames=
Session\Port=22555
Session\QueueingSystemEnabled=true
Session\SSL\Port=57672
Session\ShareLimitAction=Stop
Session\TempPath=/downloads/temp
Session\TorrentContentLayout=Subfolder

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=@Invalid()

[RSS]
AutoDownloader\DownloadRepacks=false
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
